import React from 'react';
import { Award, CheckCircle, AlertTriangle, MessageSquare } from 'lucide-react';

export function parseCriticReview(reviewText) {
  if (!reviewText) return null;

  const result = {
    score: null,
    strengths: [],
    improvements: [],
    verdict: ""
  };

  const lines = reviewText.split('\n');
  let currentSection = "";

  for (let rawLine of lines) {
    const trimmed = rawLine.trim();
    if (!trimmed) continue;

    // Check for Score
    const scoreMatch = trimmed.match(/Score:\s*([\d.]+)\s*\/10/i) || trimmed.match(/Score:\s*([\d.]+)/i);
    if (scoreMatch && result.score === null) {
      result.score = parseFloat(scoreMatch[1]);
      continue;
    }

    // Determine active section
    if (/strengths/i.test(trimmed)) {
      currentSection = "strengths";
      continue;
    } else if (/areas to improve|areas for improvement|improvement/i.test(trimmed)) {
      currentSection = "improvements";
      continue;
    } else if (/verdict|one line verdict/i.test(trimmed)) {
      currentSection = "verdict";
      continue;
    }

    // Clean markdown characters from list item content
    const cleanContent = trimmed.replace(/^[-*•\s]+/, '').replace(/[*#`_]/g, '').trim();
    if (!cleanContent) continue;

    if (currentSection === "strengths") {
      result.strengths.push(cleanContent);
    } else if (currentSection === "improvements") {
      result.improvements.push(cleanContent);
    } else if (currentSection === "verdict") {
      if (result.verdict) {
        result.verdict += " " + cleanContent;
      } else {
        result.verdict = cleanContent;
      }
    }
  }

  // Fallback for score parsing if regex fails
  if (result.score === null) {
    result.score = 5.0; // neutral fallback
  }

  return result;
}

export default function CriticReview({ reviewText }) {
  const data = parseCriticReview(reviewText);
  if (!data) return null;

  const percentScore = (data.score / 10) * 100;
  
  // Choose color based on score
  let scoreColorClass = "text-red-400";
  let scoreBgClass = "bg-red-500/10";
  let scoreBorderClass = "border-red-500/30";
  let progressColorClass = "bg-red-500";
  
  if (data.score >= 7.5) {
    scoreColorClass = "text-[#50c878]";
    scoreBgClass = "bg-[#50c878]/10";
    scoreBorderClass = "border-[#50c878]/30";
    progressColorClass = "bg-[#50c878]";
  } else if (data.score >= 5.0) {
    scoreColorClass = "text-yellow-400";
    scoreBgClass = "bg-yellow-500/10";
    scoreBorderClass = "border-yellow-500/30";
    progressColorClass = "bg-yellow-500";
  }

  return (
    <div className="flex flex-col gap-6 rounded-2xl bg-white/[0.02] border border-white/10 p-6 md:p-8">
      {/* Header section with Score */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4">
        <div>
          <h4 className="font-syne font-bold text-lg text-[#f0ebe0]">Automated Peer Review</h4>
          <p className="text-xs text-[#a09890] font-mono mt-0.5">GENERATED BY CRITIC CHAIN AGENT</p>
        </div>
        
        {/* Score Badge */}
        <div className={`flex items-center gap-2.5 px-4 py-2 rounded-xl border ${scoreBgClass} ${scoreBorderClass}`}>
          <Award className={`w-5 h-5 ${scoreColorClass}`} />
          <div className="flex flex-col">
            <span className="text-[10px] font-mono text-[#a09890] uppercase tracking-wider leading-none">Score</span>
            <span className={`text-lg font-bold font-mono ${scoreColorClass} leading-tight`}>
              {data.score} <span className="text-xs text-[#a09890]/60 font-normal">/ 10</span>
            </span>
          </div>
        </div>
      </div>

      {/* Score Progress Bar */}
      <div className="flex flex-col gap-1.5">
        <div className="flex justify-between text-xs font-mono text-[#a09890]">
          <span>Review Rating</span>
          <span>{data.score * 10}%</span>
        </div>
        <div className="h-2 w-full bg-white/5 rounded-full overflow-hidden">
          <div 
            className={`h-full ${progressColorClass} transition-all duration-500`} 
            style={{ width: `${percentScore}%` }}
          />
        </div>
      </div>

      {/* Grid for Strengths & Areas to Improve */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div className="flex flex-col gap-3 p-5 rounded-xl bg-[#50c878]/[0.02] border border-[#50c878]/10">
          <div className="flex items-center gap-2 text-[#50c878] font-mono text-xs uppercase tracking-widest font-bold">
            <CheckCircle className="w-4 h-4" />
            Key Strengths
          </div>
          {data.strengths.length > 0 ? (
            <ul className="flex flex-col gap-2">
              {data.strengths.map((item, idx) => (
                <li key={idx} className="text-sm text-[#cdc8bf] leading-relaxed flex items-start gap-2">
                  <span className="text-[#50c878] mt-1">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-[#a09890] italic">No specific strengths listed.</p>
          )}
        </div>

        {/* Improvements */}
        <div className="flex flex-col gap-3 p-5 rounded-xl bg-yellow-500/[0.02] border border-yellow-500/10">
          <div className="flex items-center gap-2 text-yellow-400 font-mono text-xs uppercase tracking-widest font-bold">
            <AlertTriangle className="w-4 h-4" />
            Areas to Improve
          </div>
          {data.improvements.length > 0 ? (
            <ul className="flex flex-col gap-2">
              {data.improvements.map((item, idx) => (
                <li key={idx} className="text-sm text-[#cdc8bf] leading-relaxed flex items-start gap-2">
                  <span className="text-yellow-400 mt-1">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-[#a09890] italic">No specific improvements listed.</p>
          )}
        </div>
      </div>

      {/* Verdict Panel */}
      {data.verdict && (
        <div className="flex flex-col gap-2 p-4 rounded-xl bg-white/[0.02] border border-[#ff8c32]/10">
          <div className="flex items-center gap-2 text-[#ff8c32] font-mono text-xs uppercase tracking-widest font-bold">
            <MessageSquare className="w-4 h-4" />
            Verdict
          </div>
          <p className="text-sm text-[#e8e4dc] leading-relaxed italic">
            "{data.verdict}"
          </p>
        </div>
      )}
    </div>
  );
}
